#!/usr/bin/env python3
"""Generate a DBX skills inventory.

The script is intentionally dependency-free and can run in a bare Python 3 environment.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

OPTIONAL_DIRS = ["references", "scripts", "assets", "evals", "agents", "examples", "checklists"]


def strip_quotes(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
        return value[1:-1]
    return value


def parse_simple_yaml_map(block: str) -> dict[str, str]:
    result: dict[str, str] = {}
    lines = block.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        if not line.strip() or line.lstrip().startswith("#"):
            i += 1
            continue
        if line.startswith((" ", "\t")) or ":" not in line:
            i += 1
            continue
        key, raw_value = line.split(":", 1)
        key = key.strip()
        raw_value = raw_value.strip()
        if raw_value in {"|", ">", "|-", ">-", "|+", ">+"}:
            collected: list[str] = []
            i += 1
            while i < len(lines):
                next_line = lines[i]
                if next_line and not next_line.startswith((" ", "\t")) and ":" in next_line:
                    break
                collected.append(next_line.strip())
                i += 1
            result[key] = "\n".join(collected).strip()
            continue
        result[key] = strip_quotes(raw_value)
        i += 1
    return result


def parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    lines = text.splitlines()
    if lines and lines[0].strip() == "---":
        for idx in range(1, len(lines)):
            if lines[idx].strip() == "---":
                return parse_simple_yaml_map("\n".join(lines[1:idx])), "strict"
    match = re.search(r"^---\s+name:\s*(?P<name>\S+)\s+description:\s*(?P<desc>.*?)\s+---", text, re.S)
    if match:
        return {"name": strip_quotes(match.group("name")), "description": match.group("desc").strip()}, "nonstandard-minified"
    return {}, "missing"


def estimate_maturity(skill_dir: Path, has_skill_md: bool) -> tuple[str, str]:
    if not has_skill_md:
        return "L1", "Missing SKILL.md"
    level = 2
    evidence = ["SKILL.md"]
    if any((skill_dir / d).exists() for d in ["references", "examples", "checklists", "assets"]):
        level = max(level, 3)
        evidence.append("reference-like material")
    if (skill_dir / "scripts").exists():
        level = max(level, 4)
        evidence.append("scripts")
    if (skill_dir / "evals").exists():
        level = max(level, 5)
        evidence.append("evals")
    return f"L{level}", ", ".join(evidence)


def inspect_skill(skill_dir: Path, root: Path) -> dict[str, Any]:
    skill_md = skill_dir / "SKILL.md"
    text = skill_md.read_text(encoding="utf-8", errors="ignore") if skill_md.exists() else ""
    meta, style = parse_frontmatter(text)
    dirs = [d for d in OPTIONAL_DIRS if (skill_dir / d).exists()]
    maturity, maturity_evidence = estimate_maturity(skill_dir, skill_md.exists())
    eval_files = []
    evals_dir = skill_dir / "evals"
    if evals_dir.exists():
        eval_files = [str(p.relative_to(root)) for p in sorted(evals_dir.glob("*.json"))]
    return {
        "name": skill_dir.name,
        "path": str(skill_dir.relative_to(root)),
        "frontmatter_name": meta.get("name"),
        "description": meta.get("description", ""),
        "frontmatter_style": style,
        "line_count": len(text.splitlines()),
        "directories": dirs,
        "eval_files": eval_files,
        "maturity_estimate": maturity,
        "maturity_evidence": maturity_evidence,
    }


def scan(root: Path) -> list[dict[str, Any]]:
    skills_dir = root / "skills"
    if not skills_dir.exists():
        return []
    return [inspect_skill(path, root) for path in sorted(skills_dir.iterdir()) if path.is_dir()]


def markdown_table(items: list[dict[str, Any]]) -> str:
    lines = [
        "# Generated Skill Inventory",
        "",
        "This file is generated by `python3 scripts/skill_inventory.py --root . --format markdown`.",
        "Review it before copying anything into `DBX_SKILL_INDEX.md`.",
        "",
        "| Skill | Frontmatter | Lines | Dirs | Evals | Maturity | Description |",
        "|---|---|---:|---|---|---|---|",
    ]
    for item in items:
        desc = item["description"].replace("\n", " ").replace("|", "\\|")
        if len(desc) > 140:
            desc = desc[:137] + "..."
        dirs = ", ".join(item["directories"]) or "none"
        evals = ", ".join(Path(p).name for p in item["eval_files"]) or "none"
        lines.append(
            f"| `{item['name']}` | {item['frontmatter_style']} | {item['line_count']} | {dirs} | {evals} | {item['maturity_estimate']} | {desc} |"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a DBX skill inventory.")
    parser.add_argument("--root", default=".", help="Repository root. Default: current directory.")
    parser.add_argument("--format", choices=["markdown", "json"], default="markdown", help="Output format.")
    args = parser.parse_args()
    root = Path(args.root).resolve()
    items = scan(root)
    if args.format == "json":
        print(json.dumps({"skills": items}, ensure_ascii=False, indent=2))
    else:
        print(markdown_table(items))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
